services:
  vision:
    build: vision
    networks:
      - vision_net
    devices:
      - /dev/video0:/dev/video0

  vision-ui:
    build: vision-ui
    ports: 
      - "8501:8501"
    networks:
      - vision_net

networks:
  vision_net:
